"""Initial schema

Revision ID: ab9fec45bd4e
Revises: 
Create Date: 2026-07-15 22:52:21.032033

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ab9fec45bd4e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=255), nullable=False),
        sa.Column("actor", sa.String(length=255), nullable=True),
        sa.Column("recorded_at", sa.DateTime(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_events_event_id"), "audit_events", ["event_id"], unique=True
    )
    op.create_index(
        op.f("ix_audit_events_event_type"), "audit_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_recorded_at"),
        "audit_events",
        ["recorded_at"],
        unique=False,
    )
    op.create_table(
        "execution_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("execution_id", sa.String(length=255), nullable=False),
        sa.Column("approval_id", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("backend", sa.String(length=255), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("error_type", sa.String(length=255), nullable=True),
        sa.Column("retryable", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_execution_records_approval_id"),
        "execution_records",
        ["approval_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_execution_records_execution_id"),
        "execution_records",
        ["execution_id"],
        unique=True,
    )
    op.create_table(
        "pending_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("approval_id", sa.String(length=255), nullable=False),
        sa.Column("nonce", sa.String(length=255), nullable=False),
        sa.Column("payload_hash", sa.String(length=255), nullable=False),
        sa.Column("tool", sa.String(length=255), nullable=False),
        sa.Column("operation", sa.String(length=255), nullable=False),
        sa.Column("namespace", sa.String(length=255), nullable=False),
        sa.Column("resource", sa.String(length=255), nullable=False),
        sa.Column("raw_payload", sa.LargeBinary(), nullable=False),
        sa.Column("headers", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("failed_at", sa.DateTime(), nullable=True),
        sa.Column("approved_by", sa.String(length=255), nullable=True),
        sa.Column("execution_backend", sa.String(length=255), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pending_requests_approval_id"),
        "pending_requests",
        ["approval_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_pending_requests_created_at"),
        "pending_requests",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pending_requests_expires_at"),
        "pending_requests",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pending_requests_nonce"), "pending_requests", ["nonce"], unique=True
    )
    op.create_index(
        op.f("ix_pending_requests_status"), "pending_requests", ["status"], unique=False
    )
    op.create_table(
        "approval_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("approval_id", sa.String(length=255), nullable=False),
        sa.Column("operator", sa.String(length=255), nullable=False),
        sa.Column("approval_time", sa.DateTime(), nullable=False),
        sa.Column("signature_verified", sa.Boolean(), nullable=False),
        sa.Column("ip_address", sa.String(length=255), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["approval_id"], ["pending_requests.approval_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_approval_records_approval_id"),
        "approval_records",
        ["approval_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_approval_records_approval_id"), table_name="approval_records"
    )
    op.drop_table("approval_records")
    op.drop_index(op.f("ix_pending_requests_status"), table_name="pending_requests")
    op.drop_index(op.f("ix_pending_requests_nonce"), table_name="pending_requests")
    op.drop_index(op.f("ix_pending_requests_expires_at"), table_name="pending_requests")
    op.drop_index(op.f("ix_pending_requests_created_at"), table_name="pending_requests")
    op.drop_index(
        op.f("ix_pending_requests_approval_id"), table_name="pending_requests"
    )
    op.drop_table("pending_requests")
    op.drop_index(
        op.f("ix_execution_records_execution_id"), table_name="execution_records"
    )
    op.drop_index(
        op.f("ix_execution_records_approval_id"), table_name="execution_records"
    )
    op.drop_table("execution_records")
    op.drop_index(op.f("ix_audit_events_recorded_at"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_event_type"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_event_id"), table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
